# ================================================================================= #
#                      Конфигурация плагина MageMount v1.6                          #
#        Главный файл для управления всеми функциями, текстами и задержками.       #
# ================================================================================= #

# --- Сообщения ---
# В этом разделе настраиваются все тексты, которые видит игрок.
# Плагин поддерживает:
#   - Стандартные цветовые коды: &a, &l, &o, &r и т.д.
#   - RGB-цвета в HEX-формате: &#RRGGBB (например, &#FF4500 для оранжевого).
# Логика обработки цветов: используется ПЕРВЫЙ цветовой код в строке. 
# Все последующие коды ЦВЕТА будут проигнорированы, но коды ФОРМАТИРОВАНИЯ (&l, &r) останутся.
messages:
  # Подсказка, которая появляется внизу экрана, когда игрок наводит курсор на сущность.
  ride-hint: "&e&lПКМ&r&7, чтобы оседлать"
  
  # Подсказка, которая появляется, когда игрок уже едет на ком-то.
  dismount-hint: "&#FF4500&lЛевый Шифт&r&7, чтобы слезть"
  
  # Сообщение, когда игрок пытается что-то сделать во время кулдауна.
  # Доступные плейсхолдеры:
  #   %time% - оставшееся время в секундах.
  on-cooldown: "&cПодождите еще %time% сек."

  # Сообщение, когда время поездки истекло и игрока автоматически спешило.
  auto-dismount: "&6Время вашей поездки истекло!"

  # Сообщение, когда у игрока закончились попытки оседлания.
  # Доступные плейсхолдеры:
  #   %uses%      - оставшееся количество поездок.
  #   %max_uses%  - максимальное количество поездок.
  no-uses-left: "&cУ вас не осталось попыток оседлания. (%uses%/%max_uses%)"

  # --- Сообщения для админских команд ---
  # Сообщения, которые видят администраторы при использовании команды /magemount.
  admin-commands:
    # Сообщение после успешной перезагрузки конфига.
    reload-success: "&a[MageMount] Конфигурация успешно перезагружена!"
    
    # Сообщение, если у игрока нет прав на команду.
    no-permission: "&c[MageMount] У вас нет прав для выполнения этой команды."
    
    # Подсказка по использованию основной команды.
    usage: "&aИспользуйте: /magemount <reload|uses>"
    
    # Подсказка по использованию подкоманды /uses.
    uses-usage: "&cИспользование: /magemount uses <player> [check|set|add|reset] [amount]"
    
    # Сообщение, если указанный игрок никогда не заходил на сервер.
    # Доступные плейсхолдеры:
    #   %player% - ник игрока.
    player-not-found: "&cИгрок %player% не найден."
    
    # Сообщение при проверке количества поездок игрока.
    # Доступные плейсхолдеры:
    #   %player%    - ник игрока.
    #   %uses%      - текущее количество поездок.
    #   %max_uses%  - максимальное количество поездок.
    uses-check: "&aИгрок %player% имеет %uses%/%max_uses% поездок."
    
    # Сообщение после сброса поездок игрока до максимума.
    # Доступные плейсхолдеры:
    #   %player% - ник игрока.
    uses-reset: "&aПоездки игрока %player% сброшены."
    
    # Сообщение, когда не указано количество для команд set/add.
    uses-no-amount: "&cУкажите количество."
    
    # Сообщение после установки определенного количества поездок.
    # Доступные плейсхолдеры:
    #   %player% - ник игрока.
    #   %amount% - установленное количество.
    uses-set: "&aУстановлено %amount% поездок для игрока %player%."
    
    # Сообщение после добавления поездок игроку.
    # Доступные плейсхолдеры:
    #   %player% - ник игрока.
    #   %amount% - добавленное количество.
    #   %total%  - итоговое количество.
    uses-add: "&aДобавлено %amount% поездок для игрока %player%. Итого: %total%."
    
    # Сообщение, если в качестве количества было введено не число.
    uses-not-a-number: "&cКоличество должно быть числом."

# --- Временная езда ---
temporary-ride:
  enabled: true
  duration-seconds: 60

# --- Ограничитель поездок ---
ride-limiter:
  enabled: true
  max-uses: 10
  reset-interval-minutes: 120

# --- Кулдауны (Задержки) ---
cooldowns:
  ride-seconds: 3
  dismount-seconds: 2

# --- Основные настройки ---
settings:
  enabled: true
  check-distance: 7
  update-interval-ticks: 5

# --- Функционал ---
features:
  ride-players: true
  ride-mobs: true

# --- Черный список ---
blacklist:
  - "WITHER"
  - "ENDER_DRAGON"